### ISSUE TITLE
Plugins not connecting

### ISSUE THREAD

**Issue by netrebin** [qwc-services/qwc-admin-gui#56]
Greetings!

I'm using qwc-docker service. Try to enable plugins (themes and config_editor) in tenantConfig.json
```json
"name": "adminGui",
      "config": {
        "db_url": "postgresql:///?service=qwc_configdb",
        "config_generator_service_url": "http://qwc-config-service:9090",
        "totp_enabled": false,
        "user_info_fields": [],
        "proxy_url_whitelist": [],
        "proxy_timeout": 60,
        "plugins": ["themes", "config_editor"],
        "input_config_path": "/srv/qwc_service/config-in",
        "qwc2_path": "/qwc2/",
        "qgs_resources_path": "/data",
        "ogc_service_url": "/ows/"
```
Config_editor plugin is appear but I have message '[Errno 2] No such file or directory: '/srv/qwc_service/config-in/default/tenantConfig.json''
![image](https://user-images.githubusercontent.com/46519545/205105394-80a4fe91-d32b-41d0-b0a5-ae40520d4a1f.png)
Themes plugin doesn't work
What am I doing wrong?

**Comment by tpo** [comment]
You need to attach the directory containing `config-in/` to `/srv/qwc_service/config-in/` that is you need to add that to the container's docker-compose configuration.

**Comment by netrebin** [comment]
> You need to attach the directory containing `config-in/` to `/srv/qwc_service/config-in/` that is you need to add that to the container's docker-compose configuration.
Thanks for the answer, but an error occurs when trying to save the result of editing the file (tenantConfig.json
 or config.json)
![image](https://user-images.githubusercontent.com/46519545/205889659-ff5b48f6-1089-4a2c-8f81-dc25fec140eb.png)

I add permissions:
```bash
sudo chown -R 33:33 volumes/attachments
sudo chown -R 33:33 volumes/config
sudo chown -R 33:33 volumes/qgs-resources
sudo chown -R 33:33 volumes/qwc2/assets
```
docker-compose.yaml:
```yaml
 qwc-admin-gui:
    restart: always
    image: sourcepole/qwc-admin-gui:v2022.09.15
    environment:
      <<: *qwc-service-variables
      # Don't enable JWT CSRF protection for admin gui, it conflicts with CSRF protection offered by Flask-WTF
      JWT_COOKIE_CSRF_PROTECT: 'False'
      USER_INFO_FIELDS: '[{"title": "Surname", "name": "surname", "type": "text", "required": true}, {"title": "First name", "name": "first_name", "type": "text", "required": true}, {"title": "Street", "name": "street", "type": "text"}, {"title": "ZIP", "name": "zip", "type": "text"}, {"title": "City", "name": "city", "type": "text"}]'
      #TOTP_ENABLED: 'False'
      GROUP_REGISTRATION_ENABLED: 'True'
      #IDLE_TIMEOUT: 600
      DEFAULT_LOCALE: 'en'
      MAIL_SUPPRESS_SEND: 'True'
      MAIL_DEFAULT_SENDER: 'from@example.com'
    # ports:
    #   - "127.0.0.1:5031:9090"
    volumes:
      - ./pg_service.conf:/srv/pg_service.conf:ro
      - ./volumes/config:/srv/qwc_service/config:ro
      # required by themes plugin:
      - ./volumes/config-in:/srv/qwc_service/config-in:ro
      - ./volumes/config:/srv/qwc_service/config-out
      - ./volumes/qwc2:/qwc2
```
Part of tenantConfig.json:
```json
{
      "name": "adminGui",
      "config": {
        "db_url": "postgresql:///?service=qwc_configdb",
        "config_generator_service_url": "http://qwc-config-service:9090",
        "totp_enabled": false,
        "user_info_fields": [],
        "proxy_url_whitelist": [],
        "proxy_timeout": 60,
        "admin_gui_title": "Admins",
        "admin_gui_subtitle": "Generates",
        "plugins": ["config_editor", "themes"], 
        "input_config_path": "/srv/qwc_service/config-in",
        "qwc2_path": "/qwc2/",
        "qgs_resources_path": "/data",
        "ogc_service_url": "/ows/"
      }
```
But the Themes plugin is still not active
